######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 24 23:34:10 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += body.h result.h setmap.h setting.h sq.h
SOURCES += body.cpp main.cpp result.cpp setmap.cpp sq.cpp
