######################################################################
# Automatically generated by qmake (3.0) ?? 8? 29 20:59:37 2016
######################################################################

TEMPLATE = app
TARGET = ommymine
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += body.h result.h setmap.h setting.h sq.h
SOURCES += body.cpp main.cpp result.cpp setmap.cpp sq.cpp
